.TH CREATE-GAME 1 "February 2026" "proton-run" "User Commands"

.SH NAME
proton-run \- run app using Proton

.SH SYNOPSIS
.B proton-run
.RI [ options ]

.SH DESCRIPTION
.B proton-run
run application via Proton
based on the provided parameters.

.SH OPTIONS
.TP
.BR \-p " " \fIprefix_name\fR
Prefix name

.TP
.BR \-h
Show help information and exit.

.SH SEE ALSO
.BR proton (1),
.BR steam (1)

.SH AUTHOR
Written by Kiryl Lutsyk.

.SH LICENSE
MIT License.
